##这是第一步，编写配置文件
#数据库配置
spring:
  datasource:
    url: jdbc:mysql://rm-bp12zpk7uiinzhj32so.mysql.rds.aliyuncs.com:3306/wpf_test?characterEncoding=utf8&useSSL=false
    username: wpf
    password: Wpf19810627
    driver-class-name: com.mysql.cj.jdbc.Driver

  #模板配置
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    #    cache: false #关闭缓存,实际环境中true

  #jpa配置
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update #create
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher #springboot 2.6.3集成swagger3启动失败解决方案
#    static-path-pattern: '/**'
#  web:
#    upload-path: D:/data/
#    resources:
#      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 100MB
      max-request-size: 100MB
#配置服务器端口
server:
  port: 8801
